server: server.cpp worm.cpp
	g++ -std=c++11 server.cpp -o server -lpthread -lGL -lglut -lGLU

client: client.cpp worm.cpp
	g++ -std=c++11 client.cpp -o client -lpthread -lGL -lglut -lGLU

worm: worm.cpp
	g++ -std=c++11 worm.cpp -o worm -lGL -lglut -lGLU
