server: server.cpp Cars.cpp
	g++ -std=c++11 server.cpp -o server -lpthread -lGL -lglut -lGLU

client: client.cpp Cars.cpp
	g++ -std=c++11 client.cpp -o client -lpthread -lGL -lglut -lGLU

Cars: Cars.cpp
	g++ -std=c++11 Cars.cpp -o Cars -lGL -lglut -lGLU
